version: '3.5'

services:
  demo_service:
    build: ./demo_service
    container_name: web_server

  nginx_service:
    build: ./nginx
    container_name: nginx_server
    ports:
      - 0.0.0.0:80:80